- name: html to pdf
  uses: misaelnieto/web_to_pdf_action@v0.3.1
  on: [push]
  with:
    webPageURL: https://nicanorcarrascovargas.github.io/
    outputFile: ./files/cv.pdf
    usePuppeteer: true
    useScreen: true
    pdfOptions: '{"format": "Letter", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
